# Generated by Django 2.2.1 on 2019-06-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComplectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complectation', models.CharField(choices=[('duvet_cover', 'Пододеяльник'), ('sheet', 'Простынь'), ('pillowcase', 'Наволочки'), ('test', [('1', '70x70'), ('2', '150x220'), ('3', '180x220'), ('4', '200x220')])], max_length=15)),
                ('complectation_count', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)])),
                ('size', models.CharField(choices=[('1', '70x70'), ('2', '150x220'), ('3', '180x220'), ('4', '200x220')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OH', 'Полуторный'), ('DB', 'Двуспальный'), ('EU', 'Евро'), ('FM', 'Семейный')], default='OH', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/products_imgs')),
                ('price', models.PositiveSmallIntegerField()),
                ('fabric', models.CharField(blank=True, max_length=55, null=True)),
                ('available', models.BooleanField()),
                ('descripton', models.TextField(blank=True)),
                ('size', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ProductComplectation')),
                ('type', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ProductType')),
            ],
        ),
    ]
