# Generated by Django 2.2.1 on 2019-06-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190628_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuvetCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('size', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'duvet_cover',
            },
        ),
        migrations.CreateModel(
            name='Pillowcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('size', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'pillowcase',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('size', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sheet',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='ProductComplectation',
        ),
        migrations.AddField(
            model_name='product',
            name='duvet_cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.DuvetCover'),
        ),
        migrations.AddField(
            model_name='product',
            name='pillowcase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Pillowcase'),
        ),
        migrations.AddField(
            model_name='product',
            name='sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Sheet'),
        ),
    ]
