# Generated by Django 2.2.1 on 2019-06-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190628_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
