# Generated by Django 2.2.1 on 2019-06-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20190630_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
