# Generated by Django 2.2 on 2019-07-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20190720_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(editable=False, max_length=30, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
