# Generated by Django 2.2 on 2019-07-22 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duvet_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.DuvetCover', verbose_name='Пододеяльник'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pillowcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Pillowcase', verbose_name='Подушка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Sheet', verbose_name='Простынь'),
        ),
    ]
