# Generated by Django 2.2 on 2019-07-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20190722_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Towel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, null=True, verbose_name='Наименование')),
                ('size', models.CharField(blank=True, max_length=55, null=True, verbose_name='Размер')),
                ('article', models.CharField(editable=False, max_length=30, null=True, unique=True, verbose_name='Артикул')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/static/products_imgs')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('fabric', models.CharField(blank=True, max_length=55, null=True, verbose_name='Материал')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('create_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
